## YAML Template.
---
server:
    port: 8089

security:
    basic:
        enabled: false

spring:
    datasource:
        username: sa
        password: Alcatel135$
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        url: jdbc:sqlserver://172.20.19.206:1433;databaseName=ALCATEL
        
auth0:
    audience: spring-boot-jwts
    issuer: https://dclserver.auth0.com/
       
